auto: true

markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: "爱王栋"
title: 爱王栋
url: http://lovedong.wang
feed: /atom.xml
author_info: <a href="http://lovedong.wang/">王栋</a>
