auto: true

markdown: kramdown

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Dong's Blog”
title: Dong's blog
description: Everything about Mukosame.
url: http://mukosame.github.io
feed: /atom.xml
author_info: <a href="http://mukosame.github.io/">Mukosame</a>
