auto: true

markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: "爱飘艳"
title: 爱飘艳
url: http://piaoyan.wang
feed: /atom.xml
author_info: <a href="http://piaoyan.wang/">飘艳</a>
